---
title: 课程考核
author: huhuaping
date: '2022-02-28'
slug: chapter01-course-eval
categories:
  - Course
tags:
  - DMD
subtitle: ''
summary: ''
authors: [胡华平]
lastmod: '2022-03-28T18:00:18+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
linktitle: 课程考核
menu:
  course-or:
    parent: 数据、模型与决策(简介)
    weight: 2
math: true
type: docs
---



## **论文模板**

《数据、模型与决策》课程考核采用“课程论文”方式进行考核。请大家下载如下**论文模板**并按要求写作和提交：

- **2022年春季MBA《数据、模型与决策》课程论文模板.docx**（[点击下载](/course-or/material/dmd-2021-2022-2-sheet.docx)）



## 一、**论文要求**：

- （1）请结合工作实际，撰写《数据、模型与决策》的相关商业经济分析案例论文一篇。

- （2）案例要有商业经济事实的基本情况描述，变量的设置、模型的构建，求解结果及其对结果的进一步分析。

- （3）论文字数5000字左右。请直接在本word文档下开始正文写作！


## 二、**论文提交**：

- （1）论文格式word文档（不建议WPS），严格命名为：`年级-班级-学号-姓名.docx`（例如：21级MBA-05班-21050408-张三.docx）

- （2）各班班长或负责人按班收齐后，打包压缩命名为：`年级-班级-DMD课程论文.zip`（例如：`21级MBA-05班-DMD课程论文.zip`。

- （3）各班班长或负责人按班收齐后，请在截止日期**2022年7月11日（周一）**前发送到邮箱：37532013\@qq.com（胡老师）

## 三、**写作话题**：

各位学员可以结合各位任课老师的授课ppt内容，参考选择如下话题（包括但不限于）之一开展论文内容写作：

- （1）各种线性规划及灵敏度分析：线性规划在市场营销、财政、生产管理、收益管理等方面的应用；数据包络分析(DEA)；收益管理；投资组合模型和资产分配；博弈分析等。

- （2）运输问题和网络模型：指派问题；最短路径问题；最小生成树问题；最大流问题等。

- （3）整数线性规划分析：全整数线性规划；0-1变量整数线性规划（如资金预算、固定成本核算、分布系统设计、银行选址、产品设计和市场份额等）。

- （4）非线性最优化分析：证券基金管理；投资组合；预测新产品等。

- （5）项目安排：活动时间确定或不确定下的活动安排；时间与成本抉择分析等。

- （6）库存模型及分析：经济订货批量模型分析；经济生产批量模型分析；有计划缺货时的库存模型分析；EOQ模型的数量折扣分析；概率需求下的库存模型分析；概率需求下的定期检查模型分析等。

- （7）等候线性模型分析

- （8）模拟分析

- （9）决策分析

- （10）时间序列分析与预测

- （11）其他相关话题



## 四、**大纲及规范**：

下面提纲和体例规范供参考：

- （1）论文题目（示例）：**XXXX公司XXXX项目活动安排及优化分析**

- （2）论文摘要和关键词

```
1.引言

2.案例背景及现实问题

3.研究目标与分析模型

4.数据获取与统计分析

5.模型求解过程与结论

  5.1 模型设定
  5.2 模型求解
  5.3 主要结论

6.政策建议

参考文献

附录材料

```

- （3）建议使用`管理科学家工具(mst)`（软件及安装见[课程说明链接](/course-or/03-slide-class/00-course-schedule.html#15)）进行模型分析和求解。当然学员也可以自由使用自己擅长的分析工具和软件（如matlab、stata、python等）。

- （4）论文正文中：a.公式必须使用公式编辑器进行编写（如mathtype或word自带公式工具）；b.表格按**三线表**样式，且表序号按`"表1 变量说明"`的方式依次编号；c.图片要尽量清晰简洁，且图序号按`"图1 产品特征关系图"`的方式依次编号。

- （5）参考文献：请按`《参考文献格式国家标准GB T7714-2015》`样式（参看pdf[点击下载](/course-or/material/china-national-standard-gb-t-7714-2015.pdf)），英文在前、中文在后，按作者拼音排序。
