---
title: 软件操作与案例应用
date: "2021-09-09T00:00:00+08:00"
draft: false
linktitle: 课程作业
menu:
  course-econometrics-master:
    parent: 中级计量经济(简介)
    weight: 30
#toc: true
type: docs
math: true
---

**训练理念**：基于具体问题，打开计量“黑箱”！一套具体理论，一个分析案例，一份代码文本。让理论真正用于实践！


**建议软件**：

- （开源）R编程语言（下载[CRAN](https://cran.r-project.org/)）

- （开源）Python编程语言

- （商业）Stata （建议安装MP 17.0版本及以上）

- （商业）EViews （建议安装10.0版本及以上）

> 说明：本人多年使用R编程语言，欢迎加入我的R世界小粉圈[Rworld](https://rworld.huhuaping.com/)

## `作业1`：函数形式及计算（必做）

（1）**作业目标**：基本OLS回归；多种函数形式比较；斜率和弹性计算。

（2）**作业任务**：题目及答题纸`.docx`文件下载（[homework-01-classic-model-computation.docx](/course-econometrics-master/homework/hw01-model-forms/homework-01-classic-model-computation.docx)）

（3）**作业数据集**：`.xlsx`数据文件下载（[lab01-dataset-family-spends.xlsx](/course-econometrics-master/homework/hw01-model-forms/lab01-dataset-family-spends.xlsx)）

（4）**截止时间**：第二周周末，具体见“作业任务”文档。

（5）**提交方式**：发送电子邮件，具体见“作业任务”文档。

## `作业2`：多元回归及矩阵计算（必做）

（1）**作业目标**：多元OLS回归；虚拟变量设定；矩阵计算。

（2）**作业任务**：题目及答题纸`.docx`文件下载（[homework-02-LR-matrix.docx](/course-econometrics-master/homework/hw02-LR-matrix/homework-02-LR-matrix.docx)）

（3）**作业数据集**：`.xlsx`数据文件下载（[lab02-dataset-cps.xlsx](/course-econometrics-master/homework/hw02-LR-matrix/lab02-dataset-cps.xlsx)）

（4）**截止时间**：第二周周末，具体见“作业任务”文档。

（5）**提交方式**：发送电子邮件，具体见“作业任务”文档。

## `作业3`：内生变量与工具变量方法（选做）

（1）**作业目标**：内生变量；工具变量；两阶段回归。

（2）**作业任务**：题目及答题纸`.docx`文件下载（[homework-03-iv-system.docx](/course-econometrics-master/homework/hw03-iv-system/homework-03-iv-system.docx)）

（3）**作业数据集**：每个同学的数据集都不同，请按下面说明找到自己的数据文件！！

- **学硕班**的学生：请先下载数据集`.zip`压缩文件（[card1995-fall-2023-academic.zip](/course-econometrics-master/homework/hw03-iv-system/card1995-fall-2023-academic.zip)）；然后解压缩zip文件；最后根据自己的学号，找到属于自己的数据文件`.xlsx`（例如：学号为`2023051398`的学硕学生，其配套的数据为`card1995_academic_2023051398.xlsx`）

- **专硕班**的学生：请先下载数据集`.zip`压缩文件（[card1995-fall-2023-major.zip](/course-econometrics-master/homework/hw03-iv-system/card1995-fall-2023-major.zip)）；然后解压缩zip文件；最后根据自己的学号，找到属于自己的数据文件`.xlsx`（例如：学号为`2023056584`的专硕学生，其配套的数据为`card1995_major_2023056584.xlsx`）

（4）**截止时间**：第二周周末，具体见“作业任务”文档。

（5）**提交方式**：发送电子邮件，具体见“作业任务”文档。