---
title: 中级计量经济学教学大纲
date: "2022-08-27T00:00:00+08:00"
draft: false
type: docs
linktitle: 教学大纲
menu:
  course-econometrics-master:
    parent: 中级计量经济(简介)
    weight: 10
output:
  blogdown::html_page:
    toc: false
    number_sections: false
math: true
---

#  个人课程网站

>**说明**：
1. 个人开发的独立网站，应用R编程语言和Rmarkdown语言开发建设；
2. 只要设备能联网，就等浏览课程资源（建议使用chrome浏览器）；
3. 连接速度根据你的电信供应商而定。

**PC电脑**访问网站：

- 使用浏览器（chrome或360极速浏览器）登陆个人网站网址[https://home.huhuaping.com/](https://home.huhuaping.com/)

# 课程简介

计量经济学是以一定的经济理论和实际的统计资料为基础，运用数学、统计学方法与计算机技术，以建立计量经济模型为主要手段，定量分析研究具有随机性特征的经济变量关系的学科。

本课程以中级水平为主，适当回顾初级课程内容，对高级课程内容稍加涉及，以经典线性模型为主，适当介绍一些适用的非经典模型。课程简单回顾了经典的单方程计量经济学模型的理论方法，详细介绍了联立方程计量经济学模型、时间序列分析模型和离散变量回归模型的理论方法，引入了几类扩展的单方程计量经济学模型；在计量经济学应用模型中，以生产函数模型、需求函数模型、消费函数模型和宏观计量经济模型为例，介绍应用模型的建立与发展。

本课程旨在通过系统的方法训练，使研究生掌握现代计量经济学研究和分析的基本原理、方法、模型及其应用，掌握运用计量经济方法进行经济学定量实证分析的能力。

# 课程学时及课程考核

课程学时：

- 学硕及博士班：48学时

- 专硕班：32学时

**课程考核方式**

本门课程考核方式为：平时考核+课程论文+课程考试。


$$课程总评成绩 = 平时考核成绩×20\%+课程论文×20\%+考试成绩×60\%$$

> 具体考核情况以任课老师最终通知为准。

# 任课老师及内容分工

## **模块01**：计量经济学基础

- 第01章 经典模型

- 第02章 矩阵分析

- 第03章 放宽假设

- 第04章 扩展方法

> **主讲教师**：胡华平（学硕）/白秀广（专硕）
> **讲授学时数**：12学时（学硕）/8学时（专硕）


## **模块02**：时间序列数据建模

- 基本概念

- 预测建模（AR、MA、ARIMA）

**主讲教师**：冀昊

**讲授学时数**：12学时（学硕）


## **模块02**：面板数据模型

**主讲教师**：郭亚军

**讲授学时数**：8学时（专硕）


## **模块03**：定性响应变量回归模型

- logit模型
- probit模型

**主讲教师**：丁吉萍

**讲授学时数**：12学时（学硕）/8学时（专硕）


## **模块04**：联立方程模型（SEM）

- 第17章 内生自变量问题

- 第18章 联立方程模型的问题和本质

- 第19章 联立方程模型的识别

- 第20章 联立方程模型的估计

**主讲教师**：朱玉春（学硕）/胡华平（专硕）

**讲授学时数**：12学时（学硕）/8学时（专硕）

