---
title: 本科生如何入手一个研究项目
author: huhuaping
date: '2019-10-17'
slug: how-to-do-research-for-undergraduate-students
categories:
  - Research
tags:
  - thesis
image:
  caption: ''
  focal_point: ''
---

## 怎么跟指导老师打交道？

论文选题到写作的整个流程，老师和学生能否有效沟通，很大程度上决定着研究质量改进的程度！


有两种典型的沟通状态：

- 学生很积极，一有机会就找老师谈自己的想法。但学生碰到困难就躲避，选题经常变换；学生没有全局观，经常掉入各种技术细节的泥沼，碰到问题就找老师，而不是尝试自己先想办法解决。

- 学生有了一个想法，就开始闷头做，与老师极少沟通。学生不看别人已有的研究成果（文献），或者只是粗略地看一些很浅的新闻报道。

如果是跟我沟通交流，大家一定要带问题带话题来！请按如下**“姿势”**进行：

### 第一轮沟通（谈初步想法）

这一轮沟通主要是把你的初步想法提出来，表达清楚，写得明白！可以是“拿来主义”！先模仿别人写得好的文章来！什么是比较好的文章？估计你很难判断。那么你就找期刊级别是属于**中文核心**（北大或南京大学的）、**CSSCI**、**SCI**或SSCI的！！请带如下带问题带话题来：

> 1. 老师，我想做【题目】为“XXXXXX”（题目不超过20字）的研究，我的【研究内容和设计】是XXXXXXXXXXX（不超过200字）。
2. 我是基于对这篇（或若干篇）科研文献“XXXXXXX”的阅读获得的灵感。（1）请对文献标明：期刊名、年、卷、期；（2）请提供这几篇【科研文献】的电子版（.pdf或.caj）。

**注意**：次轮沟通可能要反复进行多次。建议要**真正**地看一两篇直接相关的英文文章！！！

### 第二轮沟通（落实实证数据和分析模型）

这一步主要沟通研究的可操作性问题。一是你的实证数据（一手调查数据或者二手数据）是否拿得到？二是分析模型能不能搞得定？

> 1. 老师，我的【题目】初步定为“XXXXXXXXX”（题目不超过20字），我的研究内容和设计进一步明确了，具体是XXXXXXXXXXX（不超过200字）。——经过前面交流，不断改进！
2. 我是基于对这篇（或若干篇）【科研文献】“XXXXXXX”的阅读获得的灵感，这篇文章的**数据来源**是XXXXXXXX（不超过100字），我也能拿到这样的数据。我的数据来源是XXXXXXX。这是我初步的**【数据表】**（请提供数据.xls或.csv等）。
3. 对这篇（或若干篇）科研文献“XXXXXXX”的分析模型是XXXXX方法，我也可以用他这个方法。我的【理论模型和分析方法】具体是这样的XXXXXXXX（不超过200字）。


### 第三轮沟通（明确创新点）

注意学术规范，切忌完全复制或照搬别人的文章！！多多思考，多多分析，最后要实现“我们不一样！”！我的文章起码有一个创新点！！！

> 1. 老师，我的【题目】进一步确定为“XXXXXXXXX”（题目不超过20字），我的研究内容和设计进一步明确了，具体是XXXXXXXXXXX（不超过200字）。——经过前面交流，不断改进！
2. 我是基于对这篇（或若干篇）科研文献“XXXXXXX”的阅读获得的灵感，我跟这篇文章最大的【不同点】是XXXXXXXX（不超过200字），这就是我的创新点。

### 第四轮沟通（论文初稿，提出自己的困难和问题，尝试解决）

写作每一篇论文，必然会碰到困难和问题！不要随意就投降、屈服！先把问题指出来、列出来，然后自己尝试找到可行的解决办法！再跟老师来沟通！

> 1. 老师，这是我的【论文初稿】（要按论文写作格式和规范来！！）
2. 我的论文还有很多地方不成熟。下面是我碰到的一些【困难和问题列表和我的解决办法】XXXXXXX（不超过500字，列出一个清单来，按急迫和重要程度来列1、2、3、）。


### 第五轮沟通（论文完善、改进）

论文都是改出来的！！每次一小步，最终成大器！

> 1. 老师，这是我的【论文修改稿】。我这次的【论文改进主要有】XXXXXX（不超过200字，列出一个清单来，按修改的重要程度来列1、2、3、）。
2. 与老师沟通后，老师会进一步提出修改意见，请把老师的【修改意见】汇总起来，回去自己抓紧修改，有问题的话就继续下一轮沟通！！

## 本科生选题的基本原则

- **专业导向**：与自己所学专业相关

- **问题导向**：题目应有明确的科学问题。

- **可操作性**：数据获取可行，可以利用身边、老家等资源。

- **理论性**：科创论文不是调研报告，应有一定的理论高度。

- **具体性**：题目要具体要小，切记出现“我国”这样的宏大字眼。


## 关于选题要以“问题导向”

选题要以“问题导向”，就是说你的研究应该着眼于社会实际问题、民生疾苦问题等，目标是解释社会问题、解决社会问题、缓解民生疾苦。选题不应该空谈阔论，不能无病呻吟！

简单的比喻：

- 你现在是医生，你要研究一个病人，那首先应该搞清楚病人有什么问题（病症）？

- 你现在是研究者，你要研究一个社会现象，那你要研究的社会现象有什么实际问题？ 

建议大家多用经济学的思维来看待和思考问题。学以致用，好多同学都没有把现实问题看得足够深。

## 研究内容和研究方案的几点建议

研究方案写作中大家应反复思考如下几个问题是否能搞定：

**分析用的数据是否可行？**

- 明确数据获取方式？（问卷调研/统计数据/商业统计数据/网络爬取数据）
- 明确要获得多少数据样本？（样本数/年度数据/月度数据/周数据……，有多少样本点？）
- 明确数据变量有哪些？（如影响因素变量都有哪些？能得到数据么？）


**研究的理论问题与实证模型是否一致？**

- 有没有一个相对明确的分析思路？（如绩效分析需要AHP层次分析法）
- 在这个分析思路下，有没有找到一个对应的分析模型？（如logistics模型等）


**研究内容提纲是否明确和具体？**

- 研究内容要写具体一点，要写到三级标题（章-节-点）。

**参考文献阅读是否充分？**

- 要懂得站在巨人的肩膀上的价值！
- 要先学会“拿来主义”！
- 阅读量要足够：起码15篇中文文献，5-10篇外文文献
- 文献的质量要高：中文起码要CSSCI或中文核心期刊索引，外文文献应该是SSCI或SCI！