---
title: 在blogdown网站中展示Xaringan slide
author: huhuaping
date: '2019-03-01'
slug: post-xaringan-slide-to-website
categories:
  - R
tags:
  - Xaringan
  - Slide
  - Website
  - Static website
subtitle: ''
summary: '本文介绍如何把Xaringan 演示Slides以静态网页（static webpage）形式载入个人网站。'
authors: [胡华平]
lastmod: '2019-03-01T09:23:57+08:00'
image:
  caption: ''
  focal_point: ''
math: true
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---


**导读**：本文介绍如何把Xaringan 演示Slides以静态网页（static webpage）形式载入个人网站。

# 主要参考资料和实现办法

- Yihui Xie的[blogdown中2.7 Static files](https://bookdown.org/yihui/blogdown/static-files.html)

- 带操作过程[Embed Slides in Your Blog](https://timmastny.rbind.io/blog/embed-slides-knitr-blogdown/)

- 带各种探索尝试的[Xaringan presentations with blogdown](https://portfolio.peter-baumgartner.net/2018/07/21/presentations-with-xaringan/)

以上都有比较系统的说明，可以直接参照。

# 需求和问题列表

## 静态网页方式损失了效率。

**静态网页**，正如其名，只能相对“固定”地加载封装好的.html文件或.pdf文件之类。显然，交互性和动态性就暂时难以获得。因为我们写作Slide是在另一个repo文件夹下（repo如course-econometrics文件夹下，并使用Xaringan包），然后确认没问题后才能把渲染好的.html形式的Slide文件（一般是如02-simple-reg-basic-slide.html）拷贝到网站repo文件夹指定目录下（repo如netlify，特定目录为`\netlify\static\slides-course`）。同时，如果html文件不是完全自容的(self-container)，那你还必须把使用到的图片数据等文件夹也一同拷贝过去（这就非常糟糕了！因为你的slide制作可能会经常变动或更新）。那么要如何自动关联Xaringan（实现slide）和blogdown（实现website）呢？

当然动态性和关联性也是有成本的。如果Xaring里的文件需要渲染很久（比如ggplot作图很多，数据分析很多），那么blogsite会负担比较大。


## 知识版权的保护问题。

slide上传到website后，文字和图片等都可以任意拷贝下载。对于开源项目，这完全没毛病。但是，对于一些重视原创知识保护的人，这就是很大的“命门”了。


