---
title: git版本控制实操技巧汇总
author: huhuaping
draft: false
date: '`r Sys.Date()-1`'
slug: note-for-git-version-control-skills
categories:
  - Git
tags:
  - Github
  - Version control
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true

---

git版本控制技巧集锦

# 配置git

配置默认文本编辑器（text editor）。windows党还是自觉使用Notepad吧，免费又熟悉

- 下载安装[Notepad++](https://notepad-plus-plus.org/)（默认安装路径）

- 打开GitBash，并输入如下代码

```
$ git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"
```

配置合并检查工具（mergetool）。这个必须要图形化GUI的，p4merge就是一个不错的选择。

- 下载并安装[p4merge](https://www.perforce.com/products/helix-core-apps/merge-diff-tool-p4merge)。默认安装路径为`"C:Program Files\Perforce\p4merge.exe"`。

- 打开GitBash，并输入如下代码：

```
$ git config --global diff.tool p4merge
$ git config --global difftool.p4merge.path 'C:\Program Files\Perforce\p4merge.exe'

$ git config --global merge.tool p4merge
$ git config --global mergetool.p4merge.path 'C:\Program Files\Perforce\p4merge.exe'
```

# gitbash常用文件及文件夹命令

1. `cd`: change directory的简写，改变目录的意思，就是切换到哪个目录下， 如 cd e:\fff  切换 E 盘下面的fff 目录。

2. `cd ..`: 回退到上一个目录。我们在写js，引入文件时，.. 表示的就是上一个目录, 所以 cd .. 回退到上一个目录就很好理解了。注意，cd 和两个点点..之间有一个空格,  

3. `pwd`: print working directory, 打印工作目录，它会显示我们当前所在的目录路径。

4. `ls`: list, 列出当前目录中的所有文件，     只不过ll(两个ll)列出的内容更为详细。

5. `touch`: 新建一个文件如 touch index.js就会在当前目录下新建一个index.js文件。

6. `rm`:  remove，删除一个文件, rm index.js 就会把index.js文件删除.

7. `mkdir`: make directory 新建一个目录,就是新建一个文件夹. 如mkdir src 新建src 文件夹.

8. `rm -r` :  删除一个文件夹， r (recusive 是递归的意思)， 删除用的就是递归，先删除文件夹里面的内容，再删除文件夹。 rm -r src 删除src目录。 

9. `mv` 移动文件, mv index.html src   index.html 是我们要移动的文件, src 是目标文件夹,当然, 这样写,必须保证文件和目标文件夹在同一目录下.

10. `reset` 清屏，把git bash命令窗口中的所有内容清空。

11. `exit` 可以直接退出窗口，

# 常用git命令

1. 视图化查看提交历史、各个分支的指向以及项目的分支分叉情况

```
$ git log --oneline --decorate --graph --all
```

# git 新挑战

## 超越github文件容量限制（单个文件50M以上）

**挑战的问题**：git bash 命令push时，如果单个文件大于50M以上，则会提示推送失败。

**参考的解决办法**包括：

- [Working with large files and repositories](https://github.community/t5/Support-Protips/Working-with-large-files-and-repositories/ba-p/9343)
    
- [Versioning large files](https://help.github.com/en/articles/versioning-large-files)



**实际的解决办法**为：

- 下载安装[git LFS软件](https://git-lfs.github.com/)

```
# git bash下确认是否成功安装

$ git lfs install
> Git LFS initialized.

```
    
- 配置[LFS存储策略](https://help.github.com/en/articles/configuring-git-large-file-storage)

```
# 追踪大容量文件所在的文件夹
$ git lfs track "data-process/"

```

- 提交并推送LFS

```
# 添加文件夹
$ git add data-process/

# 提交并推送
$ git commit -m "add LFS directory data-process/"
$ git push origin master

```

## 忽略文件设置

工作思路是：

- 在工作目录下新建`.gitigore`文件

```
$ touch .gitignore

```


- git bash调用文本编辑工具（windows死粉的notepad++），编辑并设置.gitignore文件

```
# 配置notepad（64bit system -windows）
$ alias notepad="/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe"

# 打开编辑器，设置忽略规则
$ notepad .gitignore
```

- 忽略规则的一个样例

```
# ignore the whole file directory

data-raw/

# ignore Rproj user info file

.Rproj.user

```