---
title: '计量经济学的那点调性和套路'
author: huhuaping
date: '2019-03-10'
slug: chating-and-teaching-in-econometrics-manner
categories:
  - Econometrics
tags:
  - Simple regress
  - Econometrics
  - R beginer
subtitle: ''
summary: '本文对计量经济学教学提出了一些独特的看法和视角。'
authors: [胡华平]
lastmod: '2019-03-10T09:23:57+08:00'
math: true
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

> 本文对计量经济学教学提出了一些独特的看法和视角。


# 前言

在计量经济学课堂上，如果开始有一个又一个的学生不断向老师发起各种提问，这似乎是一个好的预示——至少有那么一些学生已经开始对某些“枯燥乏味”的话题开始自己的思考。

但是，也不要高兴太早。因为后面的来回反馈和互动，可能更加让人焦头烂额。情形就好比如，菜市场热闹早市下熙熙攘攘吵闹讨价的买家和卖主，各自吆喝一番，然后各得其所，好像都赚了。

计量经济学学习中有很多坑，不一一失足踏过，就千万不敢妄称深谙其道、门儿清。

# 调性

## 关于参考教材

外文原著的中文翻译版不可读，或者起码要少读少碰。一是翻译错误多（多半是态度和责任心问题）；或者译词怪异（各种创造，也不能说是谬误，就是觉得奇怪。比如`time constant variable`译成`时常变量`看起来“很妥帖”啊；又比如`innovation`译成`新息`也有相同后遗症），或者一词多译（还往往出现在同一译本下）；或者前后颠倒语句生涩（大多是生硬套译，中文里美妙的“意译”技巧好像完全施展不出来。

> ps:怀念一下傅雷翻译罗曼罗兰的《约翰克里斯多夫》，不过人家操刀上架的可是**文学**作品）。如此种种，能耐心看完的也算得上是忍性极好之人。

## 关于语言体系

计量经济学有其独特的语言体系。计量经济学充满了各类符号、记号、公式等，初接触它无异于观地外文明、听梦魇呓语。总体上看，计量经济学好似有其独特的**语言体系**。这套语言体系，主体应该以**数学语言**为其蓝本，但是又大量加入了各种神秘万千的**假设（Assumptions）**，远不如**数学语言**那么严格优美。

## 关于背景剧情

场景变幻和剧情线条很重要。模型千万个，理论各有理。同一个符号出现在A场景里，可能在B场景里就完全变了另一个含义。

比如总体回归模型（PRM）$Y_i = \beta_1 +\beta_2X_i +u_i$和样本回归模型（SRM）$Y_i = \hat{\beta}_1 + \hat{\beta}_2X_i +e_i$，两个场景下$Y_i$的含义完全不同（前者是总体$Y_i$，后者是样本$Y_i$，一般前者要包含后者的）。

另外就是要考虑讲故事的剧情。同样是表达方差，总体方差要记成$\sigma^2_{\hat{\beta}_2}=\frac{\sigma^2}{\sum{x_i^2}}$，样本方差就要记成$S^2_{\hat{\beta}_2}=\frac{\hat{\sigma}^2}{\sum{x_i^2}}$，而$\hat{\sigma}^2$又是PRM中随机干扰项$u_i$的方差的**无偏估计量**，如此这番，这个剧情和故事线的深度简直堪比HBO神剧的编剧设定，让你欲罢不能，脑细胞非要死一大片不罢休。

## 关于统计软件

统计软件上手操作，那是真的“伤痛”。`EViews`、`SPSS`之类的软件，菜单驱动的做法本质上就是给初学者完美定制了一个个“宠坏孩子”的“工具黑箱”！使用这些方便的套件久了，真的会禁锢人的思维，麻痹人类的神经。

事实上，你会发现书本上的理论和假设，跟你的实际分析案例总是那么格格不入。削足适履也好，生搬硬套也好，总觉得那那难受。

# 建议

下面说一点“建设性”的意见：

- 计量经济学原著走起吧，少年！这个舶来品，还是原汁原味的读起来更顺畅。它不能像文学作品那样，意译可以活灵活现，能植入到本土文化中并让你感同身受。它更多的是科学作品，追求严格和准确，因此直译你会水土不服（产生文化排斥），意译你会不知所云（丢失太多信息）。

- 熟悉“主流话语”，忘掉哪些非主流的“方言”吧。计量大咖们（已经被封神）的经典传世之作一定要好好拜读（`Wooldridge`、`Green`之类的），它们的“语言符号”大多经过精巧打磨，形成了、影响着、并决定着“主流话语”（官方语言）。

- 理论与实践，各露一手。熟悉一门编程统计语言（`R语言`,`Python`,`Stata`等等皆可，最好精通一门），有备无患，上能通天会仙，下能镇妖除魔。理论和实践要兼顾，相得益彰。

下面以**面板数据**（panel data analysis）的相关学习为例：

**理论**方面的书籍主要可以看：

- Wooldridge, J. M. Introductory econometrics. A modern approach(6th)  [M], Cengage Learning, 2016. 关于面板的内容，精简了很多。

- Wooldridge, J. M. Econometric Analysis of Cross Section and Panel Data 2ed  [M], MIT press, 2010. 当然是经典了，但是阅读难度较大（矩阵知识和技巧）。

- Baltagi, B. H. Econometric analysis of panel data  (5th) [M]. Chichester (West Sussex), John Wiley & Sons, Inc., 2013.

- Erik, B. Econometrics of panel data : methods and applications  [M], Oxford University Press, 2017. 作者基于40年相关教学经验，编写了这本书。作者也深切感受到矩阵知识的学习难度，尝试用尽量简单的向量符号来表达其中的精华。（可惜的是，我觉得这种勇敢的尝试并没有达到其目的。或者换句话，矩阵语言的优势是难以替代的。）

> I have experienced that many students starting on the topic feel parts of the matrix algebra, especially when written in a dense, compact style, to be an obstacle.
> -- Erik,2017


**R应用**的一些书籍可以看：

- Croissant, Y. and G. Millo. Panel data econometrics with R  [M]. Hoboken, John Wiley & Sons, 2019. 写作套路好像很不一样。

    - 随书配套有R包`pder` [(Croissant & Millo, 2017)](https://cran.r-project.org/web/packages/pder/index.html)

- Heiss, F. Using R for introductory econometrics  [M], CreateSpace Independent Publishing Platform, 2016. 内容安排与wooldridge比较一致。

    - [图书官网](http://www.urfie.net/)。里面有html在线版本，所有的数据和R程序代码。

最后，给一些资源作为有益的启示吧。

- Dave Giles 的个人blog [Econometrics Beat: Dave Giles' Blog](https://davegiles.blogspot.com/)。文如其名，踏出你的节拍击败计量经济学吧！

- 互联网世界的互动与交流，看看聊得多透彻多走心！[I Am Too Absolutely Heteroskedastic for This Probit Model](https://statmodeling.stat.columbia.edu/2011/12/08/a-short-back-and-forth-on-models-with-unequal-variances-leading-to-my-usual-suggestion-to-check-your-statistical-procedure-by-seeing-how-it-performs-on-fake-data/)


