---
title: 文献管理：Rmarkdown写作环境下的Endnote使用
author: huhuaping
date: '2020-10-03'
slug: bib-and-cite-on-research-article
categories:
  - Research
tags:
  - article
  - bibTeX
subtitle: ''
summary: '因为多年使用EndNote软件管理文献，在使用Rmarkdown写文章时，自然免不了遭遇传统与尝新的大碰撞。这篇博文记录了二者协调使用中的困难，以及基本的协作流程和注意事项。不得不承认，在软件工具使用上，我们不得不在坚守传统的“稳固性”以及拥抱创新的“生命力”之间，不断做出权衡、抉择、隐忍，直至最后的突破和归宿。对我而言，目前无疑还处在这隐忍和彻底破除的过渡时期。'
authors: []
lastmod: '2020-10-03T16:32:55+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
math: yes
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---


使用Rmarkdown写科学论文，自然避免不了管理和使用参考文献，以及文献输出样式。

# EndNote和流程

目前为止，我的唯一文献工具是**EndNote**（版本X9）。掐指一算，差不多已经坚持使用了近13年了。多年来攒下的一个文献库.enl里，文献条目多达3500条（多半是存而不读的啦）。

在使用Rmarkdown写文章后，工作流程总是免不了受这个多年的工具牵连。可行的办法如下：

1. 查找学术文献。利用谷歌学术查找文献，导入EndNote。（google学术设置里拉选一下默认导入工具）

2. 修改定制EndNote软件。Endnote里一番神设置（具体见后），获得文献条目的BibTex格式。

3. 集中注意力写文章的地方。Rmarkdown文档`.Rmd`里写文章，同时新建一个`.bib`的附带文件。

4. 管理BibTex文献的地方。把BibTex格式的文献条目，复制到`.bib`文件里面去。

5. 管理正文里文献引用显示和以及`参考文献`的输出样式。与`.Rmd`并行配置一个`.csl`文档。关于引用样式语言——Citation Style Language (CSL) ，后面再说。

目前的流程是没有可行的，但是几个问题仍旧存在：

a. EndNote重度使用的后遗症。一是要手动把EndNote文献条目的BibTeX内容复制到`.bib`里面去，太费手啦！二是，EndNote文献条目的BibTeX内容中，引用ID需要手动调整，这个也是很费手！

b. 文献管理存档的主副之争。EndNote文献条目，跟`.bib`里的文献条目是无法关联的。意味着，要同时管理两个家伙！

c. 引用样式语言Citation Style Language (CSL) 文档，可能需要定制化修改！


先不说这些血泪控诉的坑吧，下面把基本过程里的小九九暂时给记录下来。

# 配置EndNote软件（Windows系统）

修改定制EndNote软件。具体可以参考[攻略](https://www.rhizobia.co.nz/latex/convert)。

> 基本步骤大概是：
- 下载style模板，导入并保存模板；然后选用此模板
- 修改Preferences ： "modify reference types"
- 修改display fields：  "Custom1"

# EndNote里编辑条目

编辑文献条目。独立设置ID ：BibTeX里编辑。


# 定制输出和显示样式

1. 准备好输出显示样式。cls样式可以参看[样式库](https://github.com/citation-style-language/styles)

2. 设置`.Rmd`文档的yaml参数，示例如下：

```
# 一级yaml参数

biblio-style: "nnsfc.csl"
csl: "nnsfc.csl"

```

# 文献引用

直接使用条目的唯一标识。例如：

```
研究发现，balabalabala[@Birthal2011]。

```
