---
title: Chapter 19. What is the Identification Problem?
author: huhuaping
date: '2023-04-01'
slug: chapter19-identification
categories:
  - Course
tags:
  - EMIII
subtitle: ''
summary: ''
authors: [Kevin Hu]
lastmod: '2023-04-01T18:00:18+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
linktitle: Chapter19 SEM Identification
menu:
  course-em-eng:
    parent: Introducton
    weight: 19
math: true
type: docs
---

## I. Course Slides

Each of the following courseware can be used, but the first format (`Xaringan slide`)is highly recommended[^a].


**1. Interactive Slides（Xaringan html slide）**(how to use it?[^b]):`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[Chapter 19. What is the Identification Problem.html](/course-em-eng/slide-eng/SEM-slide-eng-part2-identification.html) .


**2.Traditional Slides (static PDF for print and E-learning)**:`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[Chapter 19. What is the Identification Problem.pdf](/course-em-eng/material/SEM-slide-eng-part2-identification.pdf).

The differences between the above two formats of courseware:

- The contents of both these two formats are basically the same. While the content of 'Xaringan slides' will be much richer than the 'PDFslides', and  'Xaringan slides' will be updated more frequently(there are some technical reasons).

- 'Xaringan slides' can perform some interactive operations, such as html widgets tables, dynamic drawings and code chunk display. While the 'PDF slides' is static file fundamentally, and users can not interact with the content elements.


- In fact, you can convert 'Xaringan slides' to 'PDF slides'  yourself at any time using Chrome.

- 'Xaringan slides' are suitable for interactive E-learning, while 'PDF slides' are suitable for offline printing or E-ink notation on you Pad.


<!---footnote following--->

[^a]: Slides are generated by using [Rmarkdown language](https://rmarkdown.rstudio.com/), and then Rendered by using R package [`Xaringan`](https://github.com/yihui/xaringan).

[^b]: **Usage Tips ** (for PC) : Click **Slide content area **, press ** 'F' ** key, you can watch the full screen. Press the left and rightarrow keys ($\leftarrow/\rightarrow$) to flip the page forward or backward. Hit the number key, then press ** 'Enter' ** to enter any specified page number. For example, hit the number 10 and then you will navigate to the slide page 10.

