---
title: 第05章 相关和回归分析
author: huhuaping
date: '2021-05-15'
slug: chpt05-corl-regression
categories:
  - Course
tags:
  - Statistics
subtitle: ''
summary: ''
authors: [胡华平]
lastmod: '2021-05-15T18:04:18+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
linktitle: 第05章:相关和回归分析
menu:
  course-statistics:
    parent: 统计学在线课程 (简介)
    weight: 15
math: true
type: docs
---

## 一、教学课件

以下课件都可以使用，两者可以互补，但强烈建议使用第一种类型`Xaringan slide`课件[^a]：

**PART A 全章课件（第05章 相关和回归分析）**：（文档较大，加载速度可能比较慢）

- **1.现代型课件（Xaringan slide）**（操作提示[^b]）：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-00-index.html) 

- **2.传统型课件（pdf）**：`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-00-index.pdf) （更新日期：2021.5.18）

**PART B 分节课件（第05章 相关和回归分析）**：（推荐使用，加载速度会更快）

- **5.1节 变量间关系的度量**：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-01-relationship.html) ；`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-01-relationship.pdf) （2021.5.18更新）

- **5.2节 回归分析的基本思想**：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-02-reg-basic.html) ；`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-02-reg-basic.pdf) （2021.5.18更新）

- **5.3节 OLS方法与参数估计**：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-03-reg-ols.html) ；`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-03-reg-ols.pdf) （2021.5.18更新）

- **5.4节 假设检验**：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-04-reg-hypothesis.html) ；`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-04-reg-hypothesis.pdf) （2021.5.18更新）

- **5.5节 拟合优度与残差分析**：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-05-reg-goodness.html) ；`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-05-reg-goodness.pdf) （2021.5.18更新）

- **5.6节 回归预测分析**：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-06-reg-forecast.html) ；`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-06-reg-forecast.pdf) （2021.5.18更新）

- **5.7节 回归报告解读**：`r fontawesome::fa('slideshare', fill= "blue", height='17px' )`[**html课件**](/course-statistics/03-slide-class/05-07-reg-report.html) ；`r fontawesome::fa('file-pdf', fill= "blue", height='17px' )`[**pdf课件**](/course-statistics/material/05-07-reg-report.pdf) （2021.5.18更新）


以上两种类型课件的**差异**：

- 两者的课件内容基本一致，区别有：`Xaringan slide`课件内容会相对细节更丰富一些；`Xaringan slide`课件更新频率会更高、更及时（里面有一些技术性原因）。

- `Xaringan slide`课件可以进行一些交互型操作，如表格、制图和代码展示等。`pdf`课件是静态文件，使用者不能进行内容上的交互。

- 实际上你可以随时使用`chrome`浏览器自己将`Xaringan slide`课件导出为`pdf`课件。

- `Xaringan slide`课件适合交互学习，而`pdf`课件适合线下打印或进行电子笔记。


<!---footnote following--->

[^a]:课件采用[Rmarkdown语言](https://rmarkdown.rstudio.com/)编写而成，课件`Slide`的形式由[Xaringan包](https://github.com/yihui/xaringan)渲染得到。

[^b]:**操作提示**（电脑PC端操作）：点击**课件区域**，按**`F`**键，可全屏观看。按左/右方向键（$\leftarrow/\rightarrow$），可以前进/后退翻页。敲击数字键，再按**`Enter`**可进入任意指定的页码。如，敲击数字10，观看第10页。

